### ISSUE TITLE
include privacy policy

### ISSUE THREAD

**Issue by nschloe** [paperhive/paperhive-frontend#151] opened 2015-05-04 16:58 UTC
Check
https://help.github.com/articles/github-privacy-policy/
https://orcid.org/footer/privacy-policy
http://about.scienceopen.com/wp-content/uploads/2014/11/ScienceOpen_Privacy_Policy_Global.pdf

**Comment by andrenarchy** [comment] 2016-02-17 17:51
duplicate of #135

**Closed by andrenarchy** 2016-02-17 17:51 UTC
